apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: default # This only grants permissions within the "development" namespace.
subjects:
- kind: ServiceAccount
  name: jane # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io