apiVersion: v1
kind: Service
metadata:
  name: example-prod
spec:
  #type: ClusterIP NodePort LoadBalancer ExternalName   
  selector:
    app: nginx
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: "80"