apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: node-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-example
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 90
      type: Resource