kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-example
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
