kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-example
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
