apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nginx
  name: ds-example
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        nodeType: edge    
      containers:
      - name: nginx
        image: nginx
        ports:
            - containerPort: 80
